development:
  adapter: postgresql
  database: impact-visualizer-development
  host: localhost
  pool: 100

test:
  adapter: postgresql
  database: impact-visualizer-test
  host: localhost

production:
  adapter: postgresql
  database: <%= Rails.application.credentials.database[:name] %>
  user: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: 10.0.0.3
  pool: 100

wmcloud:
  adapter: postgresql
  database: <%= Rails.application.credentials.database[:name] %>
  user: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  pool: 100